apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ingress-manager-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ingress-manager-cr
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    namespace: ingress-manager-ns
    name: ingress-manager-sa